### ISSUE TITLE
[QUESTION] App crashes when activated on CarPlay simulator, complaining about missing scene delegate

### ISSUE THREAD

**Issue by jan-happy** [birkir/react-native-carplay#68] opened 2021-10-11 15:47 UTC
Hi,
I'm using 2.0.0 with RN 0.64.2 and Xcode 13 to test on the iOS 15 simulator.
I'm fairly sure I've implemented everything according to the sample app, entitlement is present and I do nothing fancy but displaying a "Hello World" screen.
Still the app crashes as soon as I tab the app icon in the CarPlay simulator:
`'NSGenericException', reason: 'Application does not implement CarPlay template application lifecycle methods in its scene delegate.'`

I already looked into implementing the needed delegate but I wonder why it runs without all this in the example app in the first place.
Thanks for any hints!

**Comment by gavrichards** [comment] 2021-10-20 15:38
> It’s unclear at this point. I think a good test would be to see if the app works on device and without the Maps entitlement. 

It does. But then I don't have a CarPlay display connected.

The problem occurs in the simulator only when I also open the CarPlay simulator and tap the app's icon on there.

> What I know is that it won’t fly with Apple if you have a Maps entitlement for an app that doesn’t use Maps. 

Yeah that doesn't surprise me, and I don't want to have to request a maps entitlement that I'm not going to use anyway.

**Comment by gavrichards** [comment] 2021-11-08 13:49
Would any of the maintainers / contributors be able to investigate further why it appears that this package requires the `com.apple.developer.carplay-maps` entitlement even when you're not using Maps? This seems like a fairly critical flaw, and is preventing me from being able to use the package. Thanks!

**Comment by gavrichards** [comment] 2021-11-08 15:03
Thanks for re-opening @jan-happy :)

**Comment by EpsWeb** [comment] 2021-11-29 12:35
Hi there. I have same issue. It's also works also in maps entitlement, but it's not. So it will be cause problem on publishing, as I understand. So how to resolve it' anybody understood? Thanks in advance.

**Comment by EpsWeb** [comment] 2021-11-30 10:39
@gavrichards You resolve this problem? Or you have maps application?

**Comment by gavrichards** [comment] 2021-11-30 10:41
@EpsWeb No  I'm not able to solve this problem. I was hoping the maintainers of would look into this.

**Comment by gavrichards** [comment] 2022-02-10 19:13
I wish I knew. I've asked the question lots, here and on the Discord too, but I can't seem to get an answer. We're very keen to use this package but we're unable to until it works for apps without maps.

**Comment by tomdye** [comment] 2022-02-10 19:17
I'm afraid I don't know the solution to this off of the top of my head and do not have much in the way of spare time to look into it right now. Even if I did, my knowledge of the underlying native ios part of this code is limited. @birkir do you have any plans to look into this or any ideas as to what is going wrong here?

I'm aware that some people are having issues with loading the carplay simulator on M1 based macs regardless of the application type, but I believe this is a separate issue.

Can someone post a repo in which this issue is easily reproducible?

**Comment by kennyham** [comment] 2022-02-24 16:16
The problem is that if you are doing something like an audio app (or almost anything other than a maps app), then you need to support the newer scene delegate . This example code doesn't do this and that's why it is crashing: https://developer.apple.com/documentation/carplay/displaying_content_in_carplay

**Comment by rimonnassory** [comment] 2022-02-24 16:56
> The problem is that if you are doing something like an audio app (or almost anything other than a maps app), then you need to support the newer scene delegate . This example code doesn't do this and that's why it is crashing: https://developer.apple.com/documentation/carplay/displaying_content_in_carplay

So, the only thing we can do is wait for a fix for this library?

**Comment by gavrichards** [comment] 2022-03-13 23:00
> The problem is that if you are doing something like an audio app (or almost anything other than a maps app), then you need to support the newer scene delegate . This example code doesn't do this and that's why it is crashing: https://developer.apple.com/documentation/carplay/displaying_content_in_carplay

@kennyham is this something you know how to fix?

**Comment by birkir** [comment] 2022-03-22 15:39
ITS COMING  💡

**Comment by gavrichards** [comment] 2022-08-20 19:16
@birkir can you give an update please?

**Comment by birkir** [comment] 2022-08-25 10:48
The scenedelegate is already here: https://github.com/birkir/react-native-carplay/pull/85

**Closed** 2023-05-25 01:59 UTC

**Comment by fivecar** [comment] 2023-06-01 22:19
@birkir : Is it possible to use ^2.3.0 with a classic AppDelegate.m somehow? When doing so, I hit this crash. However, I don't want to switch over to an AppDelegate.swift for the same reasons that @gavrichards mentioned in #132 (e.g. wanting Siri and other launchOptions).

**Comment by ElangoPrince** [comment] 2024-04-26 12:49
@birkir Can you suggest how to use with AppDelegate.m? still awaiting for your update.

**Comment by ElangoPrince** [comment] 2024-04-26 13:12
@gavrichards  Did you solve with AppDelegate.m?

**Comment by gavrichards** [comment] 2024-04-26 13:29
> @gavrichards  Did you solve with AppDelegate.m? 

No, we switched to the new version that uses a Swift AppDelegate and Scene delegates: https://github.com/birkir/react-native-carplay/issues/68#issuecomment-1227095299

**Comment by fivecar** [comment] 2024-09-04 06:20
I've flipped over to the Swift version as well.

**Comment by naveen-chippala** [comment] 2025-05-28 11:34
i am trying to make an android auto feature to my existing react native project . I am facing many challenges during this process. Kindly provide me some resource to do a basic setup to my app of android auto.
